spotify_project:
  outputs:
    dev:
      account: "{{ env_var('SNOWFLAKE_ACCOUNT')}}"
      database: dev_spotify_data
      password: "{{ env_var('SNOWFLAKE_PASSWORD')}}"
      role: dev_role
      schema: test
      threads: 2
      type: snowflake
      user: abdkumar
      warehouse: compute_wh
      timeout_seconds: 300
  target: dev